[build]
command = "node build"
publish = "_site"

[build.processing]
skip_processing = false

[[redirects]]
from = "https://idonthaveapodcast.netlify.com/*"
to = "https://idonthaveapodcast.troyv.dev/:splat"
status = 301
force = true

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
