[build]
command = "node build"
publish = "_site"

[build.processing]
skip_processing = false

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"
